name: 10k
favicon: null
layout_spectrum: 0.3547
typography_spectrum: 0.14752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.75
  lightness: 0.4275461216457188
  saturation: 0.6021765428595245
  rhythmicContrast: 0.5
purpose: []
